build:
  nodes:
    analysis:
      tests:
        stop_on_failure: true
        override:
          - php-scrutinizer-run
      environment:
        php:
          version: '8.0.8'

before_commands:
  - 'composer update -o --prefer-source --no-interaction'

filter:
  excluded_paths:
    - 'build/*'
    - 'vendor/*'
    - 'Tests/*'

tools:
  external_code_coverage:
    timeout: 600
  php_analyzer: true
  php_code_sniffer: true
