language: php
os: linux
dist: bionic

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 8.0.1

jobs:
  fast_finish: true

before_script:
  - composer update -o --no-interaction --prefer-source

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=build/clover.xml

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/clover.xml
#  - vendor/bin/infection --threads=4 --min-msi=77 --min-covered-msi=77 --log-verbosity=none
