language: php
os: linux
dist: bionic

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 8.0.1

jobs:
  fast_finish: true

install:
  - composer update -o --no-interaction --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit --coverage-clover=build/clover.xml

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
  - vendor/bin/infection --threads=4 --min-msi=77 --min-covered-msi=77 --log-verbosity=none
