language: php
os: linux
dist: bionic

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 8.0.8
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - echo 'xdebug.mode=debug,coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - echo 'xdebug.mode=coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer update -o --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover=build/clover.xml --coverage-xml=build/coverage/coverage-xml --log-junit=build/coverage/junit.xml

after_script:
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover build/clover.xml
  - ./vendor/bin/infection --skip-initial-tests --coverage=build/coverage --threads=4 --min-msi=77 --min-covered-msi=77 --log-verbosity=none --no-interaction --no-progress
